#!/usr/bin/perl -w
#
# Reads downtimes from a nagios status.dat and creates an ical file out of it
#
# Written by Darko Krizic <darko.krizic@prodyna.com>

use strict;
use POSIX;

# ###################
# configuration start
# ###################

# process host downtimes
my $process_host_downtimes = 1;

# process service downtimes
my $process_service_downtimes = 1;

# The status.dat written by icinga 
my $status = "/var/lib/icinga/status.dat";

# The ics file to be written
my $icalendar = "/var/www/downtimes.ics";

# ###################
# configuration end
# ###################

# do not change anything down here
my $debug = 0;
my $insection = 0;
my $inhostdowntime = 0;
my $inservicedowntime = 0;
my %info = ();

open(ICAL, ">$icalendar");
print ICAL "BEGIN:VCALENDAR\n";
print ICAL "VERSION:2.0\n";
print ICAL "PRODID:-//hacksw/handcal//NONSGML v1.0//EN\n";
open(STATUS,"<$status");
while(my $line = <STATUS>) {
	chomp $line;
	$line =~ s/^\s+//; # trim start
	$line =~ s/\s+$//; # trom end
	next unless $line; # ignore empty lines
	if( $line =~ /^hostdowntime/ ) { 
		# we are in a hostdowmtime section
		$insection = 1;
		$inhostdowntime = 1;
		next;
	}
	if( $line =~ /^servicedowntime/ ) { 
		# we are in a servicedowmtime section
		$insection = 1;
		$inservicedowntime = 1;
		next;
	}
	if( $line eq "}" and $insection ) {
		# check if to create output for this section
		my $create = 0;
		$create = 1 if( $inhostdowntime && $process_host_downtimes );
		$create = 1 if( $inservicedowntime && $process_service_downtimes);
		next unless $create;

		# section is closed - write VEVENT
		print ICAL "BEGIN:VEVENT\n";
		if( $debug ) {
			foreach my $key (keys %info) {
				print "$key=$info{$key}\n";
			}	
		}
		if( $inhostdowntime ) {
			# host specific
			print ICAL "SUMMARY:Scheduled downtime $info{'host_name'}\n";
			$inhostdowntime = 0;
		} elsif( $inservicedowntime ) { 
			# service specific
			print ICAL "SUMMARY:Scheduled downtime $info{'service_description'} on $info{'host_name'}\n";
			$inservicedowntime = 0;

		} 
		# generic rest for section
		print ICAL "DTSTART:".strftime("%Y%m%dT%H%M%SZ",gmtime($info{'start_time'}))."\n";
		print ICAL "DTEND:".strftime("%Y%m%dT%H%M%SZ",gmtime($info{'end_time'}))."\n";
		print ICAL "DESCRIPTION:$info{'comment'} ($info{'author'})\n";
		print ICAL "ORGANIZER: $info{'author'}\n";
		print ICAL "END:VEVENT\n";

		# clean stored data for section
		%info = ();
		$insection = 0;
		next;
	}
	if( $insection ) {
		# store data if in section
		my ($key,$value) = split '=',$line;
		$info{$key} = $value;
	}
}
close(STATUS);
print ICAL "END:VCALENDAR\n";
close(ICAL);
